### ISSUE TITLE
static clock

### ISSUE THREAD

**Issue by mrinmox** [leonardosposina/arduino-led-dot-matrix-clock#2]
how to make the clock static on the display?

**Comment by leonardosposina** [comment]
> how to make the clock static on the display?

Hi @mrinmox, could you please give me more details about what you wanna do?

**Comment by mrinmox** [comment]
hello, @leonardosposina I want the code to display the time a bit longer because it scrolls continuously with a little bit first. So, how can I do that? And another thing is can I connect the two-dot matrix MAX7219 simultaneously at the same time?

**Comment by mrinmox** [comment]
hello, @leonardosposina I want the code to display the time a bit longer because it scrolls. So, how can I do that? And another thing is can I connect the two matrix MAX7219 simultaneously at the same time?

**Comment by leonardosposina** [comment]
Hi @mrinmox,

Sure, you can connect more MAX7219 modules to extend the display size, so you will be able to see the time information a bit longer. To do that, you just need to connect the next module in the "out" connection of the previous one, and don't forget to update these properties below in the *LEDDotMatrixClock.ino* file:

```c++
const byte H_DISPLAYS = 4; // Horizontal display blocks number
const byte V_DISPLAYS = 1; // Vertical display blocks number
...
void setup() {
...
  matrix.setPosition(0, 0, 0);
  matrix.setPosition(1, 1, 0);
  matrix.setPosition(2, 2, 0);
  matrix.setPosition(3, 3, 0);
  // should add matrix.setPosition() for new display blocks.
  matrix.setRotation(0, 1);    
  matrix.setRotation(1, 1);
  matrix.setRotation(2, 1);
  matrix.setRotation(3, 1);
  // should add matrix.setRotation()for new display blocks;
}
``` 

Regards,

Leonardo.

**Comment by mrinmox** [comment]
thank you so much
